const catcher =
	(fn) =>
	async ({ ...args }) => {
		try {
			await fn({ ...args });
		} catch (error) {
			console.info("â›” Error at query: ", error.message);
			return false;
		}
	};

module.exports = {catcher,};
